#!/usr/bin/env bash

set -e

if [ "Darwin" = "$(uname -s)" ]; then
  if [ -z $(which git) ]; then
    echo "error: git: not found"
    echo xcode-select --install
    exit 1
  fi
  if [ -z "$(which brew)" ]; then
    echo "error: brew: not found"
    echo /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    exit 1
  fi
fi

if [ -z "$(which git)" ]; then
  echo "error: git: not found"
  exit 1;
fi
if [ -z "$(which curl)" ]; then
  echo "error: curl: not found"
  exit 1;
fi
if [ -z "$(which python)" ]; then
  echo "error: python: not found"
  exit 1;
fi

if [ -z "$(which node)" ]; then
  echo "warning: node: not found"
fi

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
