- hosts: localhost
  tasks:
    - name: Install packages
      homebrew:
        name: '{{item}}'
        state: present
      with_items:
        - ansible
        - autossh
        - docker
        - docker-compose
        - gitlab-runner
        - jq
        - maven
        - mkcert
        - neovim
        - nss
        - tig
        - tmux
    - name: Install casks
      homebrew_cask:
        name: '{{item}}'
        state: present
      with_items:
        - docker
        - firefox
        - flycut
        - google-chrome
        - insomnia
        - iterm2
        - postman
        - slack
        - spectacle
        - spotify
        - tunnelblick
        - visual-studio-code

