- hosts: localhost
  tasks:
    - import_tasks: tasks/who.yml
    - import_tasks: tasks/files.yml
 
    - import_tasks: tasks/linux.yml
      when: ansible_os_family == "Debian"

    - import_tasks: tasks/mac.yml
      when: ansible_os_family == "Darwin"

    - import_tasks: tasks/unix.yml
      when:
        - ansible_os_family == "Darwin"
        - ansible_os_family == "Debian"

    - import_tasks: tasks/windows.yml
      when: ansible_os_family == "Windows"