- hosts: localhost
  tasks:
    - name: Get host user
      block:
        - name: whoami
          local_action: command whoami
          changed_when: false
          register: dotfiles_user_cmd
          check_mode: no
        - name: Set dotfiles_user
          set_fact: dotfiles_user={{dotfiles_user_cmd.stdout}}
      tags: always

    - import_tasks: tasks/files.yml

    - import_tasks: tasks/unix.yml
      when: ansible_os_family == "Darwin" or ansible_os_family == "Debian" or ansible_os_family == "RedHat"

    - import_tasks: tasks/linux.yml
      when: ansible_os_family == "Debian"

    - import_tasks: tasks/mac.yml
      when: ansible_os_family == "Darwin"

    - import_tasks: tasks/windows.yml
      when: ansible_os_family == "Windows"

    - name: Setup VSCode
      become: yes
      become_user: root
      import_role:
        name: ansible-role-visual-studio-code
      vars:
        users:
          - username: "{{dotfiles_user}}"
            visual_studio_code_extensions:
              - adamhartford.vscode-base64
              - bungcip.better-toml
              - coenraads.bracket-pair-colorizer-2
              - eamodio.gitlens
              - editorconfig.editorconfig
              - esbenp.prettier-vscode
              - dbaeumer.vscode-eslint
              - ms-azuretools.vscode-docker
              - ms-vscode-remote.vscode-remote-extensionpack
              - redhat.vscode-yaml
              - rust-lang.rust
              - skyapps.fish-vscode
              - shyykoserhiy.vscode-spotify
              - vscoss.vscode-ansible
            visual_studio_code_settings:
              {
                "breadcrumbs.enabled": true,
                "editor.tabSize": 2,
                "editor.renderWhitespace": "boundary",
                "editor.rulers": [80],
                "explorer.confirmDragAndDrop": false,
                "gitlens.mode.active": "zen",
                "terminal.integrated.shell.linux": "/usr/bin/fish",
                "terminal.integrated.shell.osx": "/usr/local/bin/fish",
                "typescript.updateImportsOnFileMove.enabled": "always",
                "workbench.startupEditor": "welcomePage",
                "files.associations": {
                  "dockerfile.*": "dockerfile"
                },
                "[typescriptreact]": {
                  "editor.defaultFormatter": "esbenp.prettier-vscode"
                },
                "[typescript]": {
                  "editor.defaultFormatter": "esbenp.prettier-vscode"
                },
                "[html]": {
                  "editor.defaultFormatter": "esbenp.prettier-vscode"
                },
                "[javascript]": {
                  "editor.defaultFormatter": "esbenp.prettier-vscode"
                },
                "[jsonc]": {
                  "editor.defaultFormatter": "esbenp.prettier-vscode"
                },
                "[json]": {
                  "editor.defaultFormatter": "esbenp.prettier-vscode"
                },
                "[yaml]": {
                  "editor.defaultFormatter": "esbenp.prettier-vscode"
                }
              }
      tags: vscode
