- hosts: localhost
  tasks:
    - name: Get host user
      block:
        - name: whoami
          local_action: command whoami
          changed_when: false
          register: dotfiles_user_cmd
        - name: Set dotfiles_user
          set_fact: dotfiles_user={{dotfiles_user_cmd.stdout}}
      tags: always
    - name: Install packages
      become: yes
      become_user: root
      apt:
        name: '{{item}}'
      with_items:
        - ansible
        - build-essential
        - curl
        - git
        - git-extras
        - git-gui
        - gitk
        - jq
        - neofetch
        - neovim
        - net-tools
        - tig
        - tmux
      tags: pkgs
    - name: Setup vi alternatives to use NeoVim
      become: yes
      become_user: root
      alternatives:
        name: vi
        path: /usr/bin/nvim
      tags: pkgs
    - name: Setup VSCode
      become: yes
      become_user: root
      import_role:
        name: ansible-role-visual-studio-code
      vars:
        users:
          - username: '{{dotfiles_user}}'
            visual_studio_code_extensions:
              - esbenp.prettier-vscode
              - dbaeumer.vscode-eslint
            visual_studio_code_settings: {
              "editor.detectIndentation": false,
              "editor.insertSpaces": false,
              "editor.fontSize": 15,
              "editor.renderWhitespace": "boundary",
              "editor.tabSize": 2,
              "editor.smoothScrolling": true,
              "terminal.integrated.fontSize": 15,
              "prettier.useTabs": true,
              "prettier.semi": false,
              "prettier.singleQuote": true,
              "prettier.trailingComma": "es5",
              "prettier.bracketSpacing": false,
              "prettier.jsxBracketSameLine": true,
              "explorer.confirmDragAndDrop": false,
              "explorer.confirmDelete": false,
              "window.menuBarVisibility": "toggle",
              "workbench.editor.showTabs": true,
              "npm.enableScriptExplorer": true
            }
      tags: vscode
    - name: Setup PATH/LD_LIBRARY_PATH to include .local/{bin,lib}
      become: yes
      become_user: '{{dotfiles_user}}'
      block:
        - file: path=~/.local/bin state=directory
        - file: path=~/.local/lib state=directory
        - blockinfile:
            path: ~/.bashrc
            insertafter: EOF
            block: |
              export PATH="~/.local/bin:$PATH"
              export LD_LIBRARY_PATH="~/.local/lib:$LD_LIBRARY_PATH"
      tags: always
    - name: Setup Vim
      become: yes
      become_user: '{{dotfiles_user}}'
      copy:
        src: files/vimrc
        dest: ~/.vimrc
      tags: always
    - name: Setup NeoVim
      become: yes
      become_user: '{{dotfiles_user}}'
      block:
        - file:
            path: ~/.config/nvim/
            state: directory
        - copy:
            src: files/init.vim
            dest: ~/.config/nvim/init.vim
      tags: always
    - name: Setup TMUX
      become: yes
      become_user: '{{dotfiles_user}}'
      copy:
        src: files/tmux.conf
        dest: ~/.tmux.conf
      tags: always
    - name: Setup Git
      become: yes
      become_user: '{{dotfiles_user}}'
      copy:
        src: files/gitconfig
        dest: ~/.gitconfig
      tags: always
