- src: https://github.com/elliotweiser/ansible-osx-command-line-tools
- src: https://github.com/gantsign/ansible-role-visual-studio-code
- src: https://github.com/geerlingguy/ansible-role-nodejs
- src: https://github.com/leanbit/ansible-nvm
- src: https://github.com/mmannerm/ansible-bash_it
