---
- name: Setup .bashrc
  become: yes
  become_user: '{{dotfiles_user}}'
  block:
    - name: ~/.config/gtk-3.0
      file: path=~/.config/gtk-3.0 state=directory
    - name: ~/.local/bin
      file: path=~/.local/bin state=directory
    - name: ~/.local/lib
      file: path=~/.local/lib state=directory
    - name: .bashrc
      blockinfile:
        path: ~/.bashrc
        insertbefore: BOF
        block: |
          [ -z $TMUX ] && tmux
          set -o vi
          bind -m vi-insert "jj":vi-movement-mode
          bind -m vi-insert "\C-l":clear-screen

          function sst() {
            if [ $# -lt 2 ]; then
              echo "Usage: sst [subdomain] [port]"
              return 1
            fi
            sub=$1
            port=$2
            autossh -R $sub:80:localhost:$port serveo.net
          }
          alias dclean="docker images -qf dangling=true | xargs -n 1 docker rmi"
          alias mon="tmux set mouse on"
          alias moff="tmux set mouse off"
          alias d="docker"
          alias dc="docker-compose"
          alias kc="kubectl"
          export EDITOR=nvim
          export PATH="$HOME/go/bin:$HOME/.local/bin:$HOME/.cargo/bin:$PATH:/Applications/Sublime Text.app/Contents/SharedSupport/bin"
          export LD_LIBRARY_PATH="~/.local/lib:$LD_LIBRARY_PATH"
  tags: always

- name: Setup Vim
  become: yes
  become_user: '{{dotfiles_user}}'
  copy:
    src: files/vimrc
    dest: ~/.vimrc
  tags: always

- name: Setup NeoVim
  become: yes
  become_user: '{{dotfiles_user}}'
  block:
    - file:
        path: ~/.config/nvim/
        state: directory
    - copy:
        src: files/init.vim
        dest: ~/.config/nvim/init.vim
  tags: always

- name: Setup TMUX
  become: yes
  become_user: '{{dotfiles_user}}'
  copy:
    src: files/tmux.conf
    dest: ~/.tmux.conf
  tags: always

- name: Setup Git
  become: yes
  become_user: '{{dotfiles_user}}'
  copy:
    src: files/gitconfig
    dest: ~/.gitconfig
  tags: always

- name: Setup Gtk
  become: yes
  become_user: '{{dotfiles_user}}'
  copy:
    src: files/gtk.css
    dest: ~/.config/gtk-3.0/gtk.css
  when: ansible_os_family == "Debian"
  tags: always
