- name: Install packages (Linux)
  become: yes
  become_user: root
  apt:
    name: '{{item}}'
  with_items:
    - autossh
    - ansible
    - build-essential
    - curl
    - fish
    - git
    - git-extras
    - git-gui
    - gitk
    - jq
    - neofetch
    - neovim
    - net-tools
    - tig
    - tmux
  tags: pkgs

- name: Change shell to fish
  become: yes
  become_user: root
  user:
    name: jonathan
    shell: /usr/bin/fish
  tags: always
