- name: Install packages
  homebrew:
    name: '{{item}}'
    state: present
  with_items:
    - ansible
    - awscli
    - autossh
    - docker
    - docker-compose
    - fzf
    - gitlab-runner
    - jq
    - maven
    - mkcert
    - neovim
    - nss
    - pipenv
    - ripgrep
    - tig
    - tmux
- name: Install casks
  homebrew_cask:
    name: '{{item}}'
    state: present
  with_items:
    - docker
    - firefox
    - flycut
    - google-chrome
    - insomnia
    - iterm2
    - postman
    - slack
    - spectacle
    - spotify
    - tunnelblick
    - visual-studio-code
