- name: "Install OSX Command Line Tools"
  become: yes
  become_user: root
  import_role:
    name: "ansible-osx-command-line-tools"

- name: Install packages (MacOS)
  homebrew:
    name: "{{item}}"
    state: present
  with_items:
    - ansible
    - autossh
    - bash
    - docker
    - docker-compose
    - fzf
    - gcc
    - gitlab-runner
    - imagemagick
    - iproute2mac
    - jq
    - kafkacat
    - kakoune
    - kubernetes-cli
    - maven
    - mkcert
    - neovim
    - nmap
    - ocaml
    - opam
    - python
    - python@2
    - reattach-to-user-namespace
    - ripgrep
    - supervisor
    - telnet
    - tig
    - tmux
    - truncate
    - watch
    - wget

- name: Install casks (MacOS)
  homebrew_cask:
    name: "{{item}}"
    state: present
  with_items:
    - alacritty
    - atom
    - brave-browser
    - disk-inventory-x
    - docker
    - firefox
    - fish
    - flycut
    - gimp
    - google-chrome
    - inkscape
    - iterm2
    - launchcontrol
    - mc
    - minikube
    - ngrok
    - obs
    - openshot-video-editor
    - postman
    - slack
    - spectacle
    - spotify
    - todotxt
    - tunnelblick
    - virtualbox
    - visual-studio-code
    - vlc
    - xquartz

- name: Add "/usr/local/bin/fish" to /etc/shells
  become: yes
  become_user: root
  lineinfile:
    path: /etc/shells
    state: present
    line: /usr/local/bin/fish
  tags: always

- name: Change shell to fish
  become: yes
  become_user: root
  user:
    name: jonathan
    shell: /usr/local/bin/fish
  tags: always
# Aliases:
# TODO: alias ports="netstat -vanp tcp"
# TODO: alias port="lsof -i tcp:3000"
