- name: Setup vi alternatives to use NeoVim
  become: yes
  become_user: root
  alternatives:
    name: vi
    path: /usr/bin/nvim
  tags: pkgs

- name: Install bash-it
  import_role:
    name: ansible-bash_it
  vars:
    users: '{{dotfiles_user}}'
    theme: minimal
  tags: [bash-it]

- name: Install Node Version Manager (nvm)
  become: yes
  become_user: root
  import_role:
    name: ansible-nvm
  vars:
    nvm_version: HEAD
    nvm_default_node_version: '10'
    nvm_node_versions: 
      - '{{nvm_default_node_version}}'
    nvm_user: '{{dotfiles_user}}'
    nvm_npm_pkgs: 
      - pkg: yarn
        version: latest
  tags: [nvm]
