- name: Setup vi alternatives to use NeoVim
  become: yes
  become_user: root
  alternatives:
    name: vi
    path: /usr/bin/nvim
  tags: pkgs
  when: ansible_os_family != "Darwin"

- name: Install bash-it
  import_role:
    name: ansible-bash_it
  vars:
    users: '{{dotfiles_user}}'
    theme: minimal
    aliases: [general]
    plugins: [alias-completion, base]
    completions:
      - awscli
      - bash-it
      - brew
      - docker-compose
      - docker-machine
      - docker
      - git
      - kubectl
      - npm
      - nvm
      - ssh
      - system
      - tmux
  tags: [bash-it]

- name: Install Node Version Manager (nvm)
  become: yes
  become_user: root
  import_role:
    name: ansible-nvm
  vars:
    nvm_version: HEAD
    nvm_default_node_version: '10'
    nvm_node_versions: 
      - '{{nvm_default_node_version}}'
    nvm_user: '{{dotfiles_user}}'
    nvm_npm_pkgs: 
      - pkg: yarn
        version: latest
  tags: [nvm]
