---
- name: Get host user
  block:
    - name: whoami
      local_action: command whoami
      changed_when: false
      register: dotfiles_user_cmd
      check_mode: no
    - name: Set dotfiles_user
      set_fact: dotfiles_user={{dotfiles_user_cmd.stdout}}
  tags: always
