- name: Install packages (Windows)
  win_chocolatey:
    name: '{{item}}'
    state: enabled
  with_items:
    - 7zip
    - curl
    - firefox
    - git
    - googlechrome
    - neovim
    - nodejs
    - putty
    - vscode
